### PR TITLE
Add Composer Support and require RapidAddOn Framework

### PR DESCRIPTION
**Pull request by claytoncollie**
Hi. This PR is for issue #26 . Add support for Composer as well utilizing Composer to require the Rapid Add On framework. This PR is only a start and will need the merging of [this PR](https://github.com/soflyy/wp-all-import-rapid-addon/pull/36) to get it working well. The main problem I found with the rapid add-on framework is that it uses `is_plugin_active` instead of `class_exists` to check if certain plugins are activated. This does not work well when using Composer and WPackagist.

### CODE REVIEW

**Comment by joeguilmette** [comment]
Thank you @claytoncollie! I've tagged @Programmer095 to have a look.

**Review by Programmer095 — CHANGES_REQUESTED** [review]
@claytoncollie Please remove all of the unnecessary composer files from your pull request.

**Comment by claytoncollie** [comment]
@Programmer095 I removed the vendor directory but left the composer lock file. With this setup, you will a need GitHub action to build the plugin before publishing to the wordpress.org repository. I suggest [this one by 10up](https://github.com/10up/action-wordpress-plugin-deploy).

**Comment by Programmer095** [comment]
This now exists in a feature branch: https://github.com/soflyy/wpai-yoast-add-on/tree/feature/composer-support

**Comment by joeguilmette** [comment]
@Programmer095 what do we need to do to get this merged and released?

**Comment by Programmer095** [comment]
> @Programmer095 what do we need to do to get this merged and released?

We need to decide if we want to include a fallback version of the Rapid Add-On API for now or set up a deployment process that adds it before deploying new versions to wordpress.org.

Also, the Rapid Add-On API repo needs to be the updated version compatible with composer since this will point to it as a source. Since it's namespaced it should be straightforward to deploy side by side with plugins using the current version. However, we may want to put some sort of version control in place as right now whichever Rapid Add-On API file loads first is the one used by all of our plugins on that site. When they're all different versions that can lead to oddities (but I don't know the best way to handle it).

**Pull request merged**
